# Generated by Django 3.1 on 2020-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='分类简介'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, max_length=50, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='分类名称'),
        ),
    ]
